name: weather_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  intl: ^0.17.0
  flutter_screenutil: ^4.0.3+3
  http: ^0.13.1
  #geolocator: ^7.0.1
  location: ^4.1.1
  flutter_native_splash: ^1.1.5+1
  flutter_dotenv: ^3.1.0
  flutter_inner_drawer: ^1.0.0+1
  launch_review: ^3.0.1
  firebase_core: ^1.0.3
  firebase_remote_config: ^0.9.0-dev.2
  # firebase_analytics: ^7.1.1
  package_info: ^2.0.0
  google_mobile_ads: ^0.12.1
  url_launcher: ^6.0.3
  permission_handler: ^6.1.3
  geocoding: ^2.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/licenses/OFL.txt
    - assets/images/039-sun.png
    - assets/images/043-warm.png
    - assets/images/048-umbrella.png
    - assets/images/weather/01d.png
    - assets/images/weather/01n.png
    - assets/images/weather/02d.png
    - assets/images/weather/02n.png
    - assets/images/weather/03d.png
    - assets/images/weather/03n.png
    - assets/images/weather/04d.png
    - assets/images/weather/04n.png
    - assets/images/weather/09d.png
    - assets/images/weather/09n.png
    - assets/images/weather/10d.png
    - assets/images/weather/10n.png
    - assets/images/weather/11d.png
    - assets/images/weather/11n.png
    - assets/images/weather/13d.png
    - assets/images/weather/13n.png
    - assets/images/weather/50d.png
    - assets/images/weather/50n.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/048-umbrella.png"
